// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEYyqSN3DXfllKlYQ7fz41eNJklJeLEmk',
    appId: '1:975968754462:web:676f94b88de806152c870f',
    messagingSenderId: '975968754462',
    projectId: 'toiletapp-dc08e',
    authDomain: 'toiletapp-dc08e.firebaseapp.com',
    storageBucket: 'toiletapp-dc08e.appspot.com',
    measurementId: 'G-B12G2DLBW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-zI7UCp1a7-Ky5lenrUGej7xTnN9VsNQ',
    appId: '1:975968754462:android:d865bbffa52a57012c870f',
    messagingSenderId: '975968754462',
    projectId: 'toiletapp-dc08e',
    storageBucket: 'toiletapp-dc08e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJEysDFIgnBHmqIFHAFaCJGfgbQ7TIAX4',
    appId: '1:975968754462:ios:4baf234a0ad709ee2c870f',
    messagingSenderId: '975968754462',
    projectId: 'toiletapp-dc08e',
    storageBucket: 'toiletapp-dc08e.appspot.com',
    iosBundleId: 'com.huudan.toiletAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJEysDFIgnBHmqIFHAFaCJGfgbQ7TIAX4',
    appId: '1:975968754462:ios:7e9a7d030c94b3f72c870f',
    messagingSenderId: '975968754462',
    projectId: 'toiletapp-dc08e',
    storageBucket: 'toiletapp-dc08e.appspot.com',
    iosBundleId: 'com.example.toiletAdmin.RunnerTests',
    
  );
}
